// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAczrdqqiASfXmv9NtlGaAol3QyPN4YTkI',
    appId: '1:932960138613:web:f6c2b6495111a810c38f3c',
    messagingSenderId: '932960138613',
    projectId: 'dastaavezain',
    authDomain: 'dastaavezain.firebaseapp.com',
    storageBucket: 'dastaavezain.firebasestorage.app',
    measurementId: 'G-R72YK4JKJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaQVualwuTpCP9gvA_2MWLV6ZBkPm-WbE',
    appId: '1:932960138613:android:962fe5e92906d2f5c38f3c',
    messagingSenderId: '932960138613',
    projectId: 'dastaavezain',
    storageBucket: 'dastaavezain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfwqaiw51NfB-iVOZQJyYqSWopDd2sn_w',
    appId: '1:932960138613:ios:e08111bbe2155740c38f3c',
    messagingSenderId: '932960138613',
    projectId: 'dastaavezain',
    storageBucket: 'dastaavezain.firebasestorage.app',
    androidClientId: '932960138613-h4f4h6pe243ibsb38ilj23g83vva51ee.apps.googleusercontent.com',
    iosClientId: '932960138613-lp66u99j36uo00q9oh6ev4k95gh42um7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dastaavezain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfwqaiw51NfB-iVOZQJyYqSWopDd2sn_w',
    appId: '1:932960138613:ios:e08111bbe2155740c38f3c',
    messagingSenderId: '932960138613',
    projectId: 'dastaavezain',
    storageBucket: 'dastaavezain.firebasestorage.app',
    androidClientId: '932960138613-h4f4h6pe243ibsb38ilj23g83vva51ee.apps.googleusercontent.com',
    iosClientId: '932960138613-lp66u99j36uo00q9oh6ev4k95gh42um7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dastaavezain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAczrdqqiASfXmv9NtlGaAol3QyPN4YTkI',
    appId: '1:932960138613:web:e0b09f661e1b178fc38f3c',
    messagingSenderId: '932960138613',
    projectId: 'dastaavezain',
    authDomain: 'dastaavezain.firebaseapp.com',
    storageBucket: 'dastaavezain.firebasestorage.app',
    measurementId: 'G-S7DW9Z7FCK',
  );
}
